"""Add bedrooms_count column to Room model

Revision ID: 4bb99d364f3d
Revises: b9e48a07a1ca
Create Date: 2025-01-15 16:55:15.300071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bb99d364f3d'
down_revision = 'b9e48a07a1ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bedrooms_count', sa.Integer(), nullable=False))
        batch_op.alter_column('room_number',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.alter_column('room_number',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.drop_column('bedrooms_count')

    # ### end Alembic commands ###
