"""added bedroom count

Revision ID: 6fe4741ca444
Revises: ef5ea84e8cbc
Create Date: 2025-01-15 16:47:36.944144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fe4741ca444'
down_revision = 'ef5ea84e8cbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bedrooms_count', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.drop_column('bedrooms_count')

    # ### end Alembic commands ###
