"""Add bedrooms_count column to Room

Revision ID: b9e48a07a1ca
Revises: 6fe4741ca444
Create Date: 2025-01-15 16:52:13.872418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9e48a07a1ca'
down_revision = '6fe4741ca444'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bedrooms_count', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.drop_column('bedrooms_count')

    # ### end Alembic commands ###
