"""updated the models

Revision ID: bdf90ff6c96e
Revises: c9361a63530c
Create Date: 2025-01-15 17:09:41.451522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdf90ff6c96e'
down_revision = 'c9361a63530c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('user_email', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('phone_number', sa.String(length=15), nullable=False))
        batch_op.add_column(sa.Column('start_date', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('end_date', sa.Date(), nullable=False))
        batch_op.drop_column('check_in_date')
        batch_op.drop_column('check_out_date')
        batch_op.drop_column('guest_name')

    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.alter_column('room_number',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=10),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.alter_column('room_number',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)

    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('guest_name', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('check_out_date', sa.DATE(), nullable=False))
        batch_op.add_column(sa.Column('check_in_date', sa.DATE(), nullable=False))
        batch_op.drop_column('end_date')
        batch_op.drop_column('start_date')
        batch_op.drop_column('phone_number')
        batch_op.drop_column('user_email')
        batch_op.drop_column('user_name')

    # ### end Alembic commands ###
