"""Add bookings relationship to Room

Revision ID: c9361a63530c
Revises: 4bb99d364f3d
Create Date: 2025-01-15 16:58:30.157165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9361a63530c'
down_revision = '4bb99d364f3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('guest_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('check_in_date', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('check_out_date', sa.Date(), nullable=False))
        batch_op.drop_column('start_date')
        batch_op.drop_column('end_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('end_date', sa.DATE(), nullable=False))
        batch_op.add_column(sa.Column('start_date', sa.DATE(), nullable=False))
        batch_op.drop_column('check_out_date')
        batch_op.drop_column('check_in_date')
        batch_op.drop_column('guest_name')

    # ### end Alembic commands ###
